//! ch17 §31 no-panic adversarial suite (T-0110): every function on
//! `prism_quant`'s public API surface (`png`, `quant`, `dither`, `pack`) must
//! resolve malformed or adversarial caller-supplied data to a typed `Err` —
//! NEVER a panic, abort, or silently-wrong success. This is the enforcement
//! test for the contract recorded in `book/17-prism-engine-architecture.md`
//! §31.
//!
//! Four corpora, each probing a different part of the public surface:
//!   A. Crafted malformed-PNG fixtures (`tests/adversarial/corpus/`,
//!      generated by the committed `generate_corpus.py`) — one fixture per
//!      declared `decode_png` rejection reason.
//!   B. The vendored PngSuite `x*` negative fixtures (T-0026), read-only.
//!   C. A deterministic truncation sweep over `corpus/seed.png` at every
//!      byte length (no runtime randomness: the sweep is a fixed `0..=len`
//!      range, committed in this source file).
//!   D. A deterministic single-bit-flip sweep over every bit of every byte
//!      of `corpus/seed.png` (same determinism argument).
//!   E. Structured adversarial calls directly against the `dither`, `pack`,
//!      and `quant` structured (non-file) public API: dimension mismatches,
//!      out-of-range parameters, and invalid enums a caller could construct
//!      without ever going through a PNG file at all.
//!
//! Every decode is wrapped in `catch_unwind` so a single panic doesn't stop
//! the sweep early — the assertion at the end of each test reports every
//! offender found in one failure, not just the first.

use prism_quant::dither::{self, RegionDirective, RegionId};
use prism_quant::pack;
use prism_quant::png::{DecodedImage, Properties, decode_png, write_indexed_png};
use prism_quant::quant::{self, MAX_COLORS};
use std::panic::{self, AssertUnwindSafe};
use std::path::{Path, PathBuf};

// --- Shared fixture plumbing -------------------------------------------------

/// The vendored PngSuite conformance corpus (`tests/pngsuite/`).
///
/// Vendored rather than read from `datasets/conformance/pngsuite/` so the suite
/// runs outside the research tree (ADR-0033 §2). PngSuite is redistributable:
/// "Permission to use, copy, modify and distribute these images for any purpose
/// and without fee is hereby granted." (c) Willem van Schaik — the upstream
/// `PngSuite.LICENSE` and `PngSuite.README` ship alongside the images.
fn pngsuite_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/pngsuite")
}

fn corpus_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/adversarial/corpus")
}

fn pngsuite_negative_fixtures() -> Vec<PathBuf> {
    let dir = pngsuite_dir();
    let mut paths: Vec<PathBuf> = std::fs::read_dir(&dir)
        .unwrap_or_else(|err| panic!("read {}: {err}", dir.display()))
        .map(|entry| entry.expect("directory entry readable").path())
        .filter(|path| {
            path.file_name()
                .and_then(|name| name.to_str())
                .is_some_and(|name| name.starts_with('x') && name.ends_with(".png"))
        })
        .collect();
    paths.sort();
    paths
}

fn crafted_fixtures() -> Vec<PathBuf> {
    let dir = corpus_dir();
    let mut paths: Vec<PathBuf> = std::fs::read_dir(&dir)
        .unwrap_or_else(|err| panic!("read {}: {err}", dir.display()))
        .map(|entry| entry.expect("directory entry readable").path())
        .filter(|path| {
            path.file_name()
                .and_then(|name| name.to_str())
                .is_some_and(|name| name.starts_with("bad-") && name.ends_with(".png"))
        })
        .collect();
    paths.sort();
    paths
}

fn seed_bytes() -> Vec<u8> {
    std::fs::read(corpus_dir().join("seed.png")).expect("read committed seed.png")
}

// --- A + B: crafted + vendored malformed-PNG corpora must never panic,
//     and must always report a clean typed Err (never a silent Ok). --------

#[test]
fn crafted_corpus_never_panics_and_always_errs() {
    let fixtures = crafted_fixtures();
    assert!(
        fixtures.len() >= 40,
        "expected the committed generator to have produced >= 40 crafted fixtures, found {}",
        fixtures.len()
    );
    let mut failures = Vec::new();
    for path in &fixtures {
        let name = path.file_name().unwrap().to_string_lossy().to_string();
        let bytes = std::fs::read(path).unwrap_or_else(|err| panic!("read {name}: {err}"));
        match panic::catch_unwind(AssertUnwindSafe(|| decode_png(&bytes))) {
            Ok(Err(_)) => {} // expected: a clean typed error
            Ok(Ok(image)) => failures.push(format!(
                "{name}: expected Err, decoded cleanly as {}x{}",
                image.width, image.height
            )),
            Err(payload) => failures.push(format!("{name}: PANIC: {}", panic_text(&payload))),
        }
    }
    assert!(
        failures.is_empty(),
        "crafted adversarial corpus violations:\n{}",
        failures.join("\n")
    );
}

#[test]
fn pngsuite_negative_fixtures_never_panic_and_always_err() {
    let fixtures = pngsuite_negative_fixtures();
    assert_eq!(
        fixtures.len(),
        14,
        "expected the vendored 14 x* PngSuite negative fixtures"
    );
    let mut failures = Vec::new();
    for path in &fixtures {
        let name = path.file_name().unwrap().to_string_lossy().to_string();
        let bytes = std::fs::read(path).unwrap_or_else(|err| panic!("read {name}: {err}"));
        match panic::catch_unwind(AssertUnwindSafe(|| decode_png(&bytes))) {
            Ok(Err(_)) => {}
            Ok(Ok(image)) => failures.push(format!(
                "{name}: expected Err, decoded cleanly as {}x{}",
                image.width, image.height
            )),
            Err(payload) => failures.push(format!("{name}: PANIC: {}", panic_text(&payload))),
        }
    }
    assert!(
        failures.is_empty(),
        "PngSuite x* negative-fixture violations:\n{}",
        failures.join("\n")
    );
}

/// Same crafted + vendored corpora through the FULL CLI-facing pipeline
/// (`quantize_png`, file-path in/out) rather than the bare decoder, so the
/// colors/policy validation and the decode-failure wrapping are exercised
/// too. Every input here is a malformed PNG, so every call must Err.
#[test]
fn full_pipeline_never_panics_on_malformed_png_files() {
    let dir = std::env::temp_dir().join(format!(
        "prism-quant-adversarial-pipeline-{}",
        std::process::id()
    ));
    std::fs::create_dir_all(&dir).expect("create scratch dir");

    let mut all_inputs = crafted_fixtures();
    all_inputs.extend(pngsuite_negative_fixtures());

    let mut failures = Vec::new();
    for (i, path) in all_inputs.iter().enumerate() {
        let name = path.file_name().unwrap().to_string_lossy().to_string();
        let in_path = dir.join(format!("in-{i}.png"));
        std::fs::copy(path, &in_path).unwrap_or_else(|err| panic!("copy {name}: {err}"));
        let out_path = dir.join(format!("out-{i}.png"));
        let result = panic::catch_unwind(AssertUnwindSafe(|| {
            quant::quantize_png(
                &in_path,
                &out_path,
                256,
                quant::DEFAULT_HIDDEN_RGB_POLICY,
                false,
                (1, 1),
                quant::DEFAULT_DITHER_POLICY,
                quant::DEFAULT_PACK_MODE,
                quant::DEFAULT_PACK_SEARCH,
            )
        }));
        match result {
            Ok(Err(_)) => {}
            Ok(Ok(summary)) => failures.push(format!(
                "{name}: expected Err, quantize_png succeeded ({} bytes out)",
                summary.output_bytes
            )),
            Err(payload) => failures.push(format!("{name}: PANIC: {}", panic_text(&payload))),
        }
    }
    let _ = std::fs::remove_dir_all(&dir);
    assert!(
        failures.is_empty(),
        "full-pipeline violations on malformed input:\n{}",
        failures.join("\n")
    );
}

// --- C: deterministic truncation sweep --------------------------------------

#[test]
fn truncation_sweep_never_panics() {
    let seed = seed_bytes();
    assert!(seed.len() > 16, "seed.png should be a real small PNG");
    // Sanity: the untruncated seed decodes cleanly (else this test would
    // vacuously pass — every prefix would correctly Err for the wrong
    // reason: a broken seed fixture, not a truncation-handling proof).
    decode_png(&seed).expect("seed.png must decode cleanly at full length");

    let mut failures = Vec::new();
    for k in 0..seed.len() {
        let prefix = &seed[..k];
        match panic::catch_unwind(AssertUnwindSafe(|| decode_png(prefix))) {
            Ok(Err(_)) => {}
            Ok(Ok(image)) => failures.push(format!(
                "truncated to {k}/{} bytes: expected Err, decoded cleanly as {}x{}",
                seed.len(),
                image.width,
                image.height
            )),
            Err(payload) => failures.push(format!(
                "truncated to {k}/{} bytes: PANIC: {}",
                seed.len(),
                panic_text(&payload)
            )),
        }
    }
    assert!(
        failures.is_empty(),
        "truncation-sweep violations ({} of {} offsets):\n{}",
        failures.len(),
        seed.len(),
        failures.join("\n")
    );
}

// --- D: deterministic single-bit-flip sweep ---------------------------------

#[test]
fn byte_flip_sweep_never_panics() {
    let seed = seed_bytes();
    decode_png(&seed).expect("seed.png must decode cleanly at full length");

    let mut failures = Vec::new();
    let mut unexpected_ok = Vec::new();
    for byte_index in 0..seed.len() {
        for bit in 0u8..8 {
            let mut mutated = seed.clone();
            mutated[byte_index] ^= 1 << bit;
            match panic::catch_unwind(AssertUnwindSafe(|| decode_png(&mutated))) {
                Ok(Err(_)) => {}
                Ok(Ok(image)) => unexpected_ok.push(format!(
                    "byte {byte_index} bit {bit}: decoded cleanly as {}x{} instead of erroring",
                    image.width, image.height
                )),
                Err(payload) => failures.push(format!(
                    "byte {byte_index} bit {bit}: PANIC: {}",
                    panic_text(&payload)
                )),
            }
        }
    }
    // A panic is always a hard failure. An unexpected clean decode is
    // reported too (structurally interesting — CRC-32 makes it exceedingly
    // unlikely a single flipped bit still yields a valid chunk stream — but
    // it is not itself a §31 violation, so it doesn't fail the build unless
    // a panic also occurred).
    if !unexpected_ok.is_empty() {
        eprintln!(
            "note: {} single-bit flip(s) decoded cleanly (not a panic, not asserted against):\n{}",
            unexpected_ok.len(),
            unexpected_ok.join("\n")
        );
    }
    assert!(
        failures.is_empty(),
        "byte-flip-sweep panics ({} of {} bit positions):\n{}",
        failures.len(),
        seed.len() * 8,
        failures.join("\n")
    );
}

fn panic_text(payload: &Box<dyn std::any::Any + Send>) -> String {
    payload
        .downcast_ref::<&str>()
        .map(|s| s.to_string())
        .or_else(|| payload.downcast_ref::<String>().cloned())
        .unwrap_or_else(|| "<non-string panic payload>".to_string())
}

// --- E: structured adversarial calls (no PNG bytes involved) ---------------

mod structured {
    use super::*;

    fn rgba(r: u8, g: u8, b: u8, a: u8) -> (u8, u8, u8, u8) {
        (r, g, b, a)
    }

    // -- png::write_indexed_png ----------------------------------------------

    #[test]
    fn write_indexed_png_rejects_degenerate_input_without_panicking() {
        let palette = vec![rgba(0, 0, 0, 255), rgba(255, 255, 255, 255)];
        #[allow(clippy::type_complexity)]
        let cases: Vec<(&str, u32, u32, Vec<(u8, u8, u8, u8)>, Vec<u8>)> = vec![
            ("zero width", 0, 2, palette.clone(), vec![0, 0]),
            ("zero height", 2, 0, palette.clone(), vec![0, 0]),
            ("empty palette", 2, 1, vec![], vec![0, 0]),
            (
                "oversized palette",
                2,
                1,
                (0..300u32).map(|i| rgba(i as u8, 0, 0, 255)).collect(),
                vec![0, 0],
            ),
            ("indices too short", 2, 1, palette.clone(), vec![0]),
            ("indices too long", 2, 1, palette.clone(), vec![0, 0, 0]),
            ("index out of range", 2, 1, palette.clone(), vec![0, 5]),
        ];
        let mut failures = Vec::new();
        for (label, width, height, palette, indices) in cases {
            match panic::catch_unwind(AssertUnwindSafe(|| {
                write_indexed_png(width, height, &palette, &indices)
            })) {
                Ok(Err(_)) => {}
                Ok(Ok(_)) => failures.push(format!("{label}: expected Err, got Ok")),
                Err(payload) => failures.push(format!("{label}: PANIC: {}", panic_text(&payload))),
            }
        }
        assert!(failures.is_empty(), "{}", failures.join("\n"));
    }

    // -- pack::pack_indexed_png -----------------------------------------------

    #[test]
    fn pack_indexed_png_rejects_degenerate_input_without_panicking() {
        let palette = vec![rgba(0, 0, 0, 255), rgba(255, 255, 255, 255)];
        #[allow(clippy::type_complexity)]
        let cases: Vec<(
            &str,
            usize,
            usize,
            Vec<(u8, u8, u8, u8)>,
            Vec<usize>,
            &str,
            &str,
        )> = vec![
            (
                "zero width",
                0,
                2,
                palette.clone(),
                vec![0, 0],
                "fast",
                "v1",
            ),
            (
                "zero height",
                2,
                0,
                palette.clone(),
                vec![0, 0],
                "fast",
                "v1",
            ),
            ("empty palette", 2, 1, vec![], vec![0, 0], "fast", "v1"),
            (
                "index out of range",
                2,
                1,
                palette.clone(),
                vec![0, 9],
                "fast",
                "v1",
            ),
            (
                "indices length mismatch",
                2,
                1,
                palette.clone(),
                vec![0],
                "fast",
                "v1",
            ),
            (
                "unknown mode",
                2,
                1,
                palette.clone(),
                vec![0, 1],
                "ludicrous",
                "v1",
            ),
            (
                "unknown search_version",
                2,
                1,
                palette.clone(),
                vec![0, 1],
                "fast",
                "v9",
            ),
        ];
        let mut failures = Vec::new();
        for (label, width, height, palette, indices, mode, search) in cases {
            match panic::catch_unwind(AssertUnwindSafe(|| {
                pack::pack_indexed_png(width, height, &palette, &indices, mode, search)
            })) {
                Ok(Err(_)) => {}
                Ok(Ok(_)) => failures.push(format!("{label}: expected Err, got Ok")),
                Err(payload) => failures.push(format!("{label}: PANIC: {}", panic_text(&payload))),
            }
        }
        assert!(failures.is_empty(), "{}", failures.join("\n"));
    }

    // -- dither module: dimension mismatches a caller could construct without
    //    ever touching a PNG file (the ch17 §31 finding this task fixed: these
    //    previously indexed out of bounds instead of erroring). -------------

    #[test]
    fn dither_functions_reject_dimension_mismatches_without_panicking() {
        let palette = vec![rgba(0, 0, 0, 255), rgba(255, 255, 255, 255)];
        let pixels_2x2: Vec<(u8, u8, u8, u8)> = vec![
            rgba(0, 0, 0, 255),
            rgba(10, 10, 10, 255),
            rgba(20, 20, 20, 255),
            rgba(30, 30, 30, 255),
        ];

        let mut failures = Vec::new();

        // floyd_steinberg: pixels shorter / longer than width*height.
        for (label, pixels, width, height) in [
            ("too few pixels", &pixels_2x2[..3], 2usize, 2usize),
            ("too many pixels", &pixels_2x2[..], 3, 3),
            ("zero width nonempty pixels", &pixels_2x2[..], 0, 4),
            ("zero height nonempty pixels", &pixels_2x2[..], 4, 0),
        ] {
            let directives = dither::stub_directives(pixels.len());
            match panic::catch_unwind(AssertUnwindSafe(|| {
                dither::floyd_steinberg(pixels, width, height, &palette, &directives)
            })) {
                Ok(Err(_)) => {}
                Ok(Ok(_)) => {
                    failures.push(format!("floyd_steinberg {label}: expected Err, got Ok"))
                }
                Err(payload) => failures.push(format!(
                    "floyd_steinberg {label}: PANIC: {}",
                    panic_text(&payload)
                )),
            }
        }

        // floyd_steinberg: region_directives length mismatched to pixels.
        let mismatched_directives = dither::stub_directives(pixels_2x2.len() + 1);
        match panic::catch_unwind(AssertUnwindSafe(|| {
            dither::floyd_steinberg(&pixels_2x2, 2, 2, &palette, &mismatched_directives)
        })) {
            Ok(Err(_)) => {}
            Ok(Ok(_)) => failures.push(
                "floyd_steinberg mismatched directive count: expected Err, got Ok".to_string(),
            ),
            Err(payload) => failures.push(format!(
                "floyd_steinberg mismatched directive count: PANIC: {}",
                panic_text(&payload)
            )),
        }

        // adaptive_strength_directives: same dimension-mismatch exposure.
        for (label, pixels, width, height) in [
            ("too few pixels", &pixels_2x2[..3], 2usize, 2usize),
            ("too many pixels", &pixels_2x2[..], 3, 3),
        ] {
            match panic::catch_unwind(AssertUnwindSafe(|| {
                dither::adaptive_strength_directives(pixels, width, height, &palette)
            })) {
                Ok(Err(_)) => {}
                Ok(Ok(_)) => failures.push(format!(
                    "adaptive_strength_directives {label}: expected Err, got Ok"
                )),
                Err(payload) => failures.push(format!(
                    "adaptive_strength_directives {label}: PANIC: {}",
                    panic_text(&payload)
                )),
            }
        }

        // region_policy_directives: same dimension-mismatch exposure.
        for (label, pixels, width, height) in [
            ("too few pixels", &pixels_2x2[..3], 2usize, 2usize),
            ("too many pixels", &pixels_2x2[..], 3, 3),
        ] {
            match panic::catch_unwind(AssertUnwindSafe(|| {
                dither::region_policy_directives(pixels, width, height, &palette)
            })) {
                Ok(Err(_)) => {}
                Ok(Ok(_)) => failures.push(format!(
                    "region_policy_directives {label}: expected Err, got Ok"
                )),
                Err(payload) => failures.push(format!(
                    "region_policy_directives {label}: PANIC: {}",
                    panic_text(&payload)
                )),
            }
        }

        // luma_bluenoise_remap: dimension, strength, and colors validation
        // precede mask loading and must remain typed errors rather than
        // indexing/arithmetic panics on direct public-API calls.
        for (label, pixels, width, height, colors, strength) in [
            (
                "too few pixels",
                &pixels_2x2[..3],
                2usize,
                2usize,
                16,
                (1, 1),
            ),
            ("too many pixels", &pixels_2x2[..], 3, 3, 16, (1, 1)),
            ("zero colors", &pixels_2x2[..], 2, 2, 0, (1, 1)),
            ("zero denominator", &pixels_2x2[..], 2, 2, 16, (1, 0)),
            ("negative numerator", &pixels_2x2[..], 2, 2, 16, (-1, 1)),
        ] {
            match panic::catch_unwind(AssertUnwindSafe(|| {
                dither::luma_bluenoise_remap(pixels, width, height, &palette, colors, strength)
            })) {
                Ok(Err(_)) => {}
                Ok(Ok(_)) => failures.push(format!(
                    "luma_bluenoise_remap {label}: expected Err, got Ok"
                )),
                Err(payload) => failures.push(format!(
                    "luma_bluenoise_remap {label}: PANIC: {}",
                    panic_text(&payload)
                )),
            }
        }

        // nearest_remap / floyd_steinberg: palette missing an alpha zone the
        // source actually uses (empty `eligible` slice) must Err, not panic.
        let opaque_only_palette = vec![rgba(0, 0, 0, 255)];
        let transparent_pixel = vec![rgba(1, 2, 3, 0)];
        match panic::catch_unwind(AssertUnwindSafe(|| {
            dither::nearest_remap(&transparent_pixel, 1, 1, &opaque_only_palette)
        })) {
            Ok(Err(_)) => {}
            Ok(Ok(_)) => {
                failures.push("nearest_remap missing alpha zone: expected Err, got Ok".to_string())
            }
            Err(payload) => failures.push(format!(
                "nearest_remap missing alpha zone: PANIC: {}",
                panic_text(&payload)
            )),
        }
        let stub = dither::stub_directives(1);
        match panic::catch_unwind(AssertUnwindSafe(|| {
            dither::floyd_steinberg(&transparent_pixel, 1, 1, &opaque_only_palette, &stub)
        })) {
            Ok(Err(_)) => {}
            Ok(Ok(_)) => failures
                .push("floyd_steinberg missing alpha zone: expected Err, got Ok".to_string()),
            Err(payload) => failures.push(format!(
                "floyd_steinberg missing alpha zone: PANIC: {}",
                panic_text(&payload)
            )),
        }
        match panic::catch_unwind(AssertUnwindSafe(|| {
            dither::adaptive_strength_directives(&transparent_pixel, 1, 1, &opaque_only_palette)
        })) {
            Ok(Err(_)) => {}
            Ok(Ok(_)) => failures.push(
                "adaptive_strength_directives missing alpha zone: expected Err, got Ok".to_string(),
            ),
            Err(payload) => failures.push(format!(
                "adaptive_strength_directives missing alpha zone: PANIC: {}",
                panic_text(&payload)
            )),
        }
        // NOTE: unlike the three calls above, `region_policy_directives`
        // legitimately returns `Ok` here: `classify_regions` assigns the
        // `Transparent` class to any zone-0 pixel unconditionally (Pass 1),
        // without ever doing a nearest-palette-entry lookup for it, so an
        // opaque-only palette never surfaces as a missing-zone error on this
        // path. Only a panic is a violation.
        match panic::catch_unwind(AssertUnwindSafe(|| {
            dither::region_policy_directives(&transparent_pixel, 1, 1, &opaque_only_palette)
        })) {
            Ok(_) => {}
            Err(payload) => failures.push(format!(
                "region_policy_directives missing alpha zone: PANIC: {}",
                panic_text(&payload)
            )),
        }

        assert!(failures.is_empty(), "{}", failures.join("\n"));
    }

    /// `RegionDirective`'s fields are all `pub`: a caller can hand-build one
    /// with a non-positive `strength_denominator` without ever going through
    /// `uniform_strength_directives` (which only ever receives an
    /// already-validated ratio inside `quantize_png`). Zero denominator is an
    /// unconditional (release-mode-too) integer-division panic in
    /// `floyd_steinberg`'s residual-diffusion arithmetic; this is the ch17
    /// §31 finding this task fixed.
    #[test]
    fn floyd_steinberg_rejects_non_positive_strength_denominator_without_panicking() {
        let palette = vec![rgba(0, 0, 0, 255), rgba(255, 255, 255, 255)];
        let pixels: Vec<(u8, u8, u8, u8)> = vec![
            rgba(0, 0, 0, 255),
            rgba(10, 10, 10, 255),
            rgba(20, 20, 20, 255),
            rgba(30, 30, 30, 255),
        ];
        let mut failures = Vec::new();
        for (label, denominator) in [("zero denominator", 0i64), ("negative denominator", -3i64)] {
            let directives = vec![
                RegionDirective {
                    region_id: RegionId::Global,
                    barrier: false,
                    strength_numerator: 1,
                    strength_denominator: denominator,
                };
                pixels.len()
            ];
            match panic::catch_unwind(AssertUnwindSafe(|| {
                dither::floyd_steinberg(&pixels, 2, 2, &palette, &directives)
            })) {
                Ok(Err(_)) => {}
                Ok(Ok(_)) => failures.push(format!("{label}: expected Err, got Ok")),
                Err(payload) => failures.push(format!("{label}: PANIC: {}", panic_text(&payload))),
            }
        }
        assert!(failures.is_empty(), "{}", failures.join("\n"));
    }

    #[test]
    fn parse_dither_strength_rejects_garbage_without_panicking() {
        let mut failures = Vec::new();
        for bad in [
            "", "abc", "1.5", "-0.5", "2", "nan", "inf", "-inf", "1e999", "..", "1.2.3", "\u{0}",
            "0x10", "1/2", "𝟏", "  ", "+-1",
        ] {
            match panic::catch_unwind(AssertUnwindSafe(|| dither::parse_dither_strength(bad))) {
                Ok(Err(_)) => {}
                Ok(Ok(ratio)) => {
                    // A handful of these ARE valid decimals in [0,1] once
                    // parsed (none in this list should be), so only flag it
                    // if truly unexpected: all listed inputs are meant to be
                    // rejected. If one is actually valid input, it belongs in
                    // a different (positive-case) test instead.
                    failures.push(format!("{bad:?}: expected Err, got Ok({ratio:?})"))
                }
                Err(payload) => failures.push(format!("{bad:?}: PANIC: {}", panic_text(&payload))),
            }
        }
        assert!(failures.is_empty(), "{}", failures.join("\n"));
    }

    // -- quant module: colors extremes + invalid policy + inconsistent
    //    DecodedImage (all `pub` fields, so any consumer can hand-build one
    //    that violates decode_png's width*height == pixels.len() invariant).

    fn tiny_decoded_image(pixels: Vec<(u8, u8, u8, u8)>, width: u32, height: u32) -> DecodedImage {
        DecodedImage {
            width,
            height,
            pixels,
            properties: Properties {
                color_type: 6,
                bit_depth: 8,
                interlaced: false,
                plte: None,
                trns: None,
                gama: None,
                iccp: None,
                conversions: vec![],
            },
        }
    }

    #[test]
    fn quantize_candidate_rejects_extreme_colors_without_panicking() {
        let source = tiny_decoded_image(
            vec![
                rgba(10, 20, 30, 255),
                rgba(40, 50, 60, 128),
                rgba(70, 80, 90, 0),
                rgba(1, 2, 3, 255),
            ],
            2,
            2,
        );
        let mut failures = Vec::new();
        for colors in [0i64, -1, -100, i64::MIN, i64::MAX, MAX_COLORS + 1] {
            match panic::catch_unwind(AssertUnwindSafe(|| {
                quant::quantize_candidate(&source, colors, quant::DEFAULT_HIDDEN_RGB_POLICY)
            })) {
                Ok(Err(_)) => {}
                Ok(Ok(_)) => failures.push(format!("colors={colors}: expected Err, got Ok")),
                Err(payload) => {
                    failures.push(format!("colors={colors}: PANIC: {}", panic_text(&payload)))
                }
            }
        }
        assert!(failures.is_empty(), "{}", failures.join("\n"));
    }

    #[test]
    fn quantize_candidate_rejects_invalid_hidden_rgb_policy_without_panicking() {
        let source = tiny_decoded_image(vec![rgba(0, 0, 0, 0), rgba(1, 1, 1, 0)], 2, 1);
        match panic::catch_unwind(AssertUnwindSafe(|| {
            quant::quantize_candidate(&source, 16, "not-a-real-policy")
        })) {
            Ok(Err(_)) => {}
            Ok(Ok(_)) => panic!("expected Err for an invalid hidden-rgb-policy, got Ok"),
            Err(payload) => panic!(
                "PANIC on invalid hidden-rgb-policy: {}",
                panic_text(&payload)
            ),
        }
    }

    #[test]
    fn quantize_candidate_rejects_invalid_color_space_without_panicking() {
        let source = tiny_decoded_image(vec![rgba(0, 0, 0, 255)], 1, 1);
        match panic::catch_unwind(AssertUnwindSafe(|| {
            quant::quantize_candidate_with_color_space(
                &source,
                16,
                quant::DEFAULT_HIDDEN_RGB_POLICY,
                "not-a-real-space",
            )
        })) {
            Ok(Err(_)) => {}
            Ok(Ok(_)) => panic!("expected Err for an invalid color-space, got Ok"),
            Err(payload) => panic!("PANIC on invalid color-space: {}", panic_text(&payload)),
        }
    }

    #[test]
    fn quantize_functions_handle_inconsistent_decoded_image_without_panicking() {
        // `DecodedImage` fields are all `pub`; a consumer can hand-build one
        // where `pixels.len() != width * height` without ever going through
        // `decode_png`'s guarantees. Neither `quantize_candidate` nor
        // `quantize_image` may panic on that, even though it is nonsensical.
        let mut failures = Vec::new();
        let inconsistent_cases = [
            (
                "declared dims larger than pixel count",
                tiny_decoded_image(vec![rgba(1, 2, 3, 255)], 4, 4),
            ),
            (
                "declared dims smaller than pixel count",
                tiny_decoded_image(
                    (0..16u32)
                        .map(|i| rgba(i as u8, i as u8, i as u8, 255))
                        .collect(),
                    2,
                    2,
                ),
            ),
            (
                "zero dims with nonempty pixels",
                tiny_decoded_image(vec![rgba(9, 9, 9, 255)], 0, 0),
            ),
            (
                "empty pixels with nonzero dims",
                tiny_decoded_image(vec![], 3, 3),
            ),
        ];
        for (label, source) in &inconsistent_cases {
            match panic::catch_unwind(AssertUnwindSafe(|| {
                quant::quantize_candidate(source, 16, quant::DEFAULT_HIDDEN_RGB_POLICY)
            })) {
                Ok(_) => {} // Ok or Err both acceptable here: only a panic is a violation.
                Err(payload) => failures.push(format!(
                    "quantize_candidate {label}: PANIC: {}",
                    panic_text(&payload)
                )),
            }
            match panic::catch_unwind(AssertUnwindSafe(|| {
                quant::quantize_image(source, 16, quant::DEFAULT_HIDDEN_RGB_POLICY)
            })) {
                Ok(_) => {}
                Err(payload) => failures.push(format!(
                    "quantize_image {label}: PANIC: {}",
                    panic_text(&payload)
                )),
            }
            match panic::catch_unwind(AssertUnwindSafe(|| {
                quant::quantize_candidate_with_color_space(
                    source,
                    16,
                    quant::DEFAULT_HIDDEN_RGB_POLICY,
                    "oklab",
                )
            })) {
                Ok(_) => {}
                Err(payload) => failures.push(format!(
                    "quantize_candidate_with_color_space(oklab) {label}: PANIC: {}",
                    panic_text(&payload)
                )),
            }
        }
        assert!(failures.is_empty(), "{}", failures.join("\n"));
    }

    #[test]
    fn quantize_png_rejects_bad_paths_and_options_without_panicking() {
        let missing = PathBuf::from("/nonexistent/path/that/should/not/exist/prism-quant-test.png");
        let out = std::env::temp_dir().join(format!(
            "prism-quant-adversarial-e-{}.png",
            std::process::id()
        ));
        let mut failures = Vec::new();
        let call = |colors: i64,
                    policy: &str,
                    dither: bool,
                    strength: (i64, i64),
                    dither_policy: &str,
                    pack_mode: &str,
                    pack_search: &str| {
            quant::quantize_png(
                &missing,
                &out,
                colors,
                policy,
                dither,
                strength,
                dither_policy,
                pack_mode,
                pack_search,
            )
        };
        #[allow(clippy::type_complexity)]
        let cases: Vec<(&str, i64, &str, bool, (i64, i64), &str, &str, &str)> = vec![
            (
                "nonexistent input path",
                256,
                "canonicalize-black",
                false,
                (1, 1),
                "uniform",
                "none",
                "v1",
            ),
            (
                "colors zero",
                0,
                "canonicalize-black",
                false,
                (1, 1),
                "uniform",
                "none",
                "v1",
            ),
            (
                "colors negative",
                -5,
                "canonicalize-black",
                false,
                (1, 1),
                "uniform",
                "none",
                "v1",
            ),
            (
                "colors i64::MAX",
                i64::MAX,
                "canonicalize-black",
                false,
                (1, 1),
                "uniform",
                "none",
                "v1",
            ),
            (
                "unknown hidden-rgb-policy",
                256,
                "bogus",
                false,
                (1, 1),
                "uniform",
                "none",
                "v1",
            ),
            (
                "unknown dither-policy",
                256,
                "canonicalize-black",
                true,
                (1, 1),
                "bogus",
                "none",
                "v1",
            ),
            (
                "unknown pack mode",
                256,
                "canonicalize-black",
                false,
                (1, 1),
                "uniform",
                "bogus",
                "v1",
            ),
            (
                "unknown pack-search",
                256,
                "canonicalize-black",
                false,
                (1, 1),
                "uniform",
                "fast",
                "bogus",
            ),
            (
                "negative strength numerator",
                256,
                "canonicalize-black",
                true,
                (-1, 2),
                "uniform",
                "none",
                "v1",
            ),
            (
                "zero strength denominator",
                256,
                "canonicalize-black",
                true,
                (1, 0),
                "uniform",
                "none",
                "v1",
            ),
            (
                "strength ratio > 1",
                256,
                "canonicalize-black",
                true,
                (3, 2),
                "uniform",
                "none",
                "v1",
            ),
        ];
        for (label, colors, policy, dith, strength, dpolicy, pmode, psearch) in cases {
            match panic::catch_unwind(AssertUnwindSafe(|| {
                call(colors, policy, dith, strength, dpolicy, pmode, psearch)
            })) {
                Ok(Err(_)) => {}
                Ok(Ok(_)) => failures.push(format!("{label}: expected Err, got Ok")),
                Err(payload) => failures.push(format!("{label}: PANIC: {}", panic_text(&payload))),
            }
        }
        let _ = std::fs::remove_file(&out);
        assert!(failures.is_empty(), "{}", failures.join("\n"));
    }
}
